#!/bin/sh

export HOME=/
export PATH=/sbin:/bin:/usr/sbin:/usr/bin

echo -n  "Mounting filesystems: "
mount -a || exit 1
echo "Done"

echo -n "Arming watchdog: "
wdogctl -u -p 40 sswdog0 && echo "Done"

echo -n "Configuring network interfaces: "
ifconfig lo0 inet 127.0.0.1 && \
route -q add -inet 127.0.0.1 -netmask 0xff000000 127.0.0.1 -reject && echo "Done"

echo -n "Starting power daemon: "
chmod +x /etc/powerd/scripts/*
powerd -d &
echo "Done"

echo -n "Starting wsmouse daemon: "
wsmoused -n &
echo "Done"

echo "Performing functionality tests: "
# Vibrator
sysctl -w hw.gta02vib0.enable=1
sleep 2
sysctl -w hw.gta02vib0.enable=0
# Red LED
sysctl -w hw.gta02leds0.red=1
sleep 2
sysctl -w hw.gta02leds0.red=0
# Orange LED
sysctl -w hw.gta02leds0.orange=1
sleep 2
sysctl -w hw.gta02leds0.orange=0
# Blue LED
sysctl -w hw.gta02leds0.blue=1
sleep 2
sysctl -w hw.gta02leds0.blue=0

echo "Connected USB devices:"
usbdevs -d

echo "Listing bluetooth devices:"
#btdevctl -A
#sysctl -a | grep ubt
btconfig -l

echo "Drivers registered with envstat framework:"
envstat -D

echo -n "Current date is: "
date

touch /var/run/dev.db
touch /var/run/utmp
touch /var/run/utmpx

cat /kern/version

echo ""
exec /bin/sh

#ttyflags -a || exit 1
#exit 0
